### ISSUE TITLE
sass-loader config options have changed

### ISSUE THREAD

**Issue by mario-minati** [jhthorsen/mojolicious-plugin-webpack#4]
Starting with `sass-loader^8.0.0` the config settings have to change like this:

```
          {
            loader: 'sass-loader',
            options: {
              sassOptions: {
                includePaths: ['absolute/path/a', 'absolute/path/b'],
              },
            },
          },
```

There is no compatibility mode AFAIK.

References:
- https://webpack.js.org/loaders/sass-loader/
- https://vuetifyjs.com/en/getting-started/quick-start#webpack-installation

**Comment by jhthorsen** [comment]
Would you mind creating a PR with the changes that you want?

**Comment by mario-minati** [comment]
The problem is that there are two different config needs. It depends on the versioning of `sass-loader`. I can make a PR to completly fix it for `8.x.x`, but than users with older versions will run into trouble.

The `webpack.config.js` is created before `sass-loader` is being installed (first time run). I'm not sure on completly rewriting the `Builder.pm` `register` functionallity.
