### ISSUE TITLE
Several vulns reported via github

### ISSUE THREAD

**Issue by toddr** [jhthorsen/mojolicious-plugin-webpack#7]
I wanted to pass these reports on from github in the event you're not getting your own reports via https://github.com/jhthorsen/mojolicious-plugin-webpack/network/alert

![Screen Shot 2020-04-03 at 8 50 30 AM](https://user-images.githubusercontent.com/97892/78367812-4ad9a100-7588-11ea-80fc-9e29ced0e449.png)

**Comment by toddr** [comment]
This was detected via https://github.com/metacpan/metacpan-cpan-extracted/

**Comment by jhthorsen** [comment]
I'm not sure if I worry too much about issues from example/tests, but I don't mind a PR to fix it.

**Comment by jhthorsen** [comment]
This should be fixed in 1.00
